### ISSUE TITLE
Support for UART hardware flow control (serial data flow control)?

### ISSUE THREAD

**Issue by Hedda** [oxan/esphome-stream-server#1]
Does this stream server custom component have support for UART hardware flow control (serial data flow control)?

This feature has also been requested here -> https://github.com/esphome/feature-requests/issues/1126

> Some devices require flow control when communicating via UART. In this case, it will be useful to add the ability to configure flow control in the UART component. ESP8266 has a hardware implementation of flow control(RTS, CTS, DTR, DSR), which is enabled through the UARTCONF register.
> This improvement will make it possible to use MAX485 for communication under the RS485 protocol.

PS: Example of MCU serial devices that can support hardware flow control with the correct firmware is Zigbee SMD modules. Ex:

https://github.com/tube0013/tube_gateways

https://www.tubeszb.com/shop/coordinators/2

https://github.com/zigpy/zigpy/discussions/584

https://github.com/zigpy/zigpy/discussions/743

**Comment by oxan** [comment]
Not specifically. This component doesn't do anything UART-specific at all, it leaves that to ESPHome. So theoretically if ESPHome sets up the UART with hardware flow control, it should work.

**Comment by oxan** [comment]
I'm going to close this, as I don't think there's anything actionable here.
