### ISSUE TITLE
Feature request: binary sensor for serial connection status

### ISSUE THREAD

**Issue by akalagov** [oxan/esphome-stream-server#8]
It would be great if you could implement a binary sensor to monitor the serial connection status. Similar functionality is implemented [here](https://github.com/thegroove/esphome-zbbridge/tree/main/custom_components/serial_server)

**Comment by joshuaspence** [comment]
@oxan Would you be open to a PR for this?

**Comment by oxan** [comment]
Yes.

**Comment by oxan** [comment]
This has now been merged.
